"""criar tabela de usuarios e fichas

Revision ID: 3c103a637d5a
Revises: 
Create Date: 2026-05-09 21:13:39.939992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c103a637d5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('quantidade_fichas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('fichas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nome_personagem', sa.String(), nullable=True),
    sa.Column('nome_jogador', sa.String(), nullable=True),
    sa.Column('vida', sa.Integer(), nullable=True),
    sa.Column('sanidade', sa.Integer(), nullable=True),
    sa.Column('classe', sa.String(), nullable=True),
    sa.Column('forca', sa.Integer(), nullable=True),
    sa.Column('agilidade', sa.Integer(), nullable=True),
    sa.Column('intelecto', sa.Integer(), nullable=True),
    sa.Column('presenca', sa.Integer(), nullable=True),
    sa.Column('vigor', sa.Integer(), nullable=True),
    sa.Column('inventario', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('defesa', sa.Integer(), nullable=True),
    sa.Column('armas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fichas_id'), 'fichas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fichas_id'), table_name='fichas')
    op.drop_table('fichas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
