"""adicionar campos ativo e admin na tabela usuarios

Revision ID: 43855b2e2e40
Revises: 3c103a637d5a
Create Date: 2026-05-19 14:52:39.983833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43855b2e2e40'
down_revision: Union[str, Sequence[str], None] = '3c103a637d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'admin')
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###
